openapi: 3.0.1
info:
  title: Gym service
  description: Gym service api document
  version: 0.1.0
servers:
- url: http://localhost
tags: []
paths:
  /api/{gymId}:
    get:
      tags:
      - api
      operationId: getGym
      parameters:
      - name: gymId
        in: path
        description: Id of the gym
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetGymResponse'
              examples:
                getGym:
                  value: |-
                    {
                      "id" : 1,
                      "name" : "name",
                      "address" : "address",
                      "description" : "description"
                    }
components:
  schemas:
    GetGymResponse:
      title: GetGymResponse
      type: object
      properties:
        price:
          type: number
          description: ""
        description:
          type: string
          description: description of the gym
        id:
          type: number
          description: id of the gym
        title:
          type: string
          description: name of the gym
