gym:
  db:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/daclimb
#    username: postgres
#    password: 1234

spring:
  datasource:
    url: jdbc:${gym.db.url}
    username: ${gym.db.username}
    password: ${gym.db.password}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: false
    baseline-on-migrate: true

  profiles:
    active: prod

cloud:
  aws:
    region:
      static: ap-northeast-2
      auto: false
    bucket: daclimb-gym-images

server:
  port: 80

management:
  endpoints:
    web:
      base-path: /

scheduler:
  image-deletion:
    time: 1


logging:
  level:
    app.gym: DEBUG

#jwt:
#  key:
#    private: <helm-secret>
#    public: <helm-secret>

jwt:
  key:
    private: ${JWT_PRIVATE}
    public: ${JWT_PUBLIC}

admin:
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}
