name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  
env:
  AWS_REGION: ap-northeast-2
  REPOSITORY: gym-service

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew clean build
    
      # Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # AWS ECR login
    - name: AWS ECR login
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # AWS ECR build and push
    - name: AWS ECR build and push
      id: ecr-build
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image_tag::$IMAGE_TAG"

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: github_alarm
        SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
        SLACK_MESSAGE: ${{steps.ecr-build.outputs.image_tag}}
        SLACK_TITLE: Image tag
        SLACK_USERNAME: ImageTagBot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.PAT }}
        repository: daclimb/api-docs
        event-type: gen-doc
        client-payload: '{"repository": "${{ github.repository }}", "ref": "${{ github.ref }}" }'

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.PAT }}
      with:
        source_file: 'openapi/openapi3.yaml'
        destination_repo: 'daclimb/api-docs'
        destination_folder: 'gym-service'
        commit_message: 'Add gym api doc'

